spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/tiny_task
        username: ozhanli
        password: ozhanli

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        hibernate:
            ddl-auto: validate

logging:
    level:
        com.coyoapp.tinytask: DEBUG
